spring:
  application:
    name: ecomarket-servicio-productos-servicios
  data:
    mongodb:
      uri: mongodb+srv://jdmolinae5:f59G7hBRJkZ9ltrg@cluster1.cxnru.mongodb.net/ecomarket?retryWrites=true&w=majority

server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://ecomarket-servicio-eureka:8761/eureka/}
  instance:
    prefer-ip-address: false
    hostname: ecomarket-servicio-productos-servicios
